version: '3.4'
services:
  tests:
    image: example
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    container_name: goexample-tests
    command: ["gotestsum", "--junitfile", "/tmp/test-reports/unit-tests.xml"]